config/routes.rb
Rails.application.routes.draw do
  resources :tailors do
    get :prices, on: :member
  end
  resources :pages
  
  namespace :dashboard do
    resources :pages
    post '/dashboard/images/new' => 'dashboard/images#new'
    resources :tailors do
      resources :addresses
      resources :prices
      resources :images do
        post :logolize, on: :member
      end
      resources :seos
      resources :opening_hours
      resources :social_connections

      patch :change_owner, on: :member
      get :change_owner_form, on: :member
    end

    resources :users
  end

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  resources :user_sessions
  resources :users

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  get 'home/access_denied' => 'home#access_denied'
  get 'home/search' => 'home#search'
  get 'home/test' => 'home#test'
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path)
    else
      flash.now[:notice] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path)
  end
end

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, :method => :postdo
  .field
    = label_tag :email
    p.control
    	= text_field_tag :email, nil, class: 'input'
  .field
    = label_tag :password
    p.control
	    = password_field_tag :password, nil, class: 'input'

  p.control
    = submit_tag "Sign in", class: 'button is-primary'

  div.notification To make this site work properly, we sometimes place small data files called cookies on your device. By <strong>signing in</strong> you accept to have our cookies on your device

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
section.section.container
	h1.title Login

	= render 'form'